# Generated by Django 5.0.dev20230830104615 on 2023-09-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0028_fullfeaturedsnippet_some_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippetchoosermodel",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
