# Generated by Django 4.0.3 on 2022-05-05 13:48

from django.db import migrations, models
import wagtail.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0068_index_customimage_file_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
            bases=(wagtail.models.RevisionMixin, models.Model),
        ),
    ]
