# Generated by Django 4.0.3 on 2022-05-05 13:48

from django.db import migrations, models
import wagtail.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0068_index_customimage_file_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
            bases=(wagtail.models.RevisionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RevisionChildModel",
            fields=[
                (
                    "revisionmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=models.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tests.revisionmodel",
                    ),
                ),
            ],
            bases=("tests.revisionmodel",),
        ),
        migrations.CreateModel(
            name="RevisionGrandChildModel",
            fields=[
                (
                    "revisionchildmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=models.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tests.revisionchildmodel",
                    ),
                ),
            ],
            bases=("tests.revisionchildmodel",),
        ),
    ]
